name: Python CI

# Déclenche le workflow sur push ou pull request sur main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest  # machine virtuelle Linux

    steps:
      # Étape 1 : récupérer le code
      - name: Checkout du code
        uses: actions/checkout@v4

      # Étape 2 : installer Python
      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Étape 3 : installer les dépendances (pytest)
      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Étape 4 : lancer les tests
      - name: Lancer les tests
        run: |
          pytest
